### PR TITLE
option for custom thumbnail

### PR DESCRIPTION
**Pull request by ayes-web**
Fixes: #30

### CODE REVIEW

**Comment by ibrahimcesar** [comment]
Thank you for the contribution! I will make a review later in the day!

**Comment by ibrahimcesar** [comment]
Thanks for the heads up @Fox32 , I have a [GitHub Action in place to publish on NPM at each release}(https://github.com/ibrahimcesar/react-lite-youtube-embed/blob/main/.github/workflows/npm-publish.yml)... but if I not change the version in the package I'm blocked to publish since npm doesn't allow the same version being published twice. So I forget to bump the package 😅 ! 

Done and released!

Thanks!

**Comment by Fox32** [comment]
Thanks!

**Comment by schoenwaldnils** [comment]
This is now breaking my build because the `thumbnail` is not optional 😅

**Pull request merged**
